---

- name: Override dhcpd.service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=DHCPv4 Server Daemon
      Documentation=man:dhcpd(8) man:dhcpd.conf(5)
      Wants=network-online.target
      After=network-online.target
      After=time-sync.target
      [Service]
      Type=notify
      EnvironmentFile=-/etc/sysconfig/dhcpd
      ExecStart=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid ens18
      StandardError=null
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/dhcpd.service
    mode: "0644"
    owner: root
    group: root
