---
- name: test dhcp-server config
  shell:
    cmd: "/usr/sbin/dhcpd -t -cf {{ dhcp_main_config4_file }}"
  listen: dhcp_restart

- name: restart dhcp-server
  service:
    name: "{{ dhcp_service }}"
    state: "{{ (dhcp_global_server_state | default('started') == 'started') | ternary('restarted', 'stopped') }}"
  listen: dhcp_restart
